import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/StoreProvider";
import Header from "@/components/Header";
import { LoadingProvider } from "@/components/LoadingProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${inter.variable} antialiased flex flex-col h-screen `}>
        <StoreProvider>
          <Header></Header>
          <LoadingProvider>
            <main className="pb-35 flex-grow overflow-x-hidden">{children}</main>
          </LoadingProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
